### ISSUE TITLE
how to display image and draw At the same time

### ISSUE THREAD

**Issue by aichy126** [adafruit/Adafruit_Python_ILI9341#11]
# Create TFT LCD display class.
disp = TFT.ILI9341(DC, rst=RST, spi=SPI.SpiDev(SPI_PORT, SPI_DEVICE, max_speed_hz=64000000))

# Initialize display.

draw = disp.draw()
# Load an image.
image = Image.open('cat.png')

# Resize the image and rotate it so it's 240x320 pixels.
image = image.rotate(90).resize((240, 320))

draw.ellipse((10, 10, 110, 80), outline=(0,255,0), fill=(0,0,255))
disp.display(image) 
disp.display()

**Comment by makermelissa** [comment]
Hi, this library is being deprecated. We're now using https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display. You can find more info in our learn guide: 
https://learn.adafruit.com/adafruit-2-dot-8-color-tft-touchscreen-breakout-v2/python-wiring-and-setup
