### ISSUE TITLE
Missing initialization step?

### ISSUE THREAD

**Issue by svenyonson** [adafruit/Adafruit_Python_ILI9341#12]
I am using the Adafruit PiTFT 2.8 (w/buttons). After changing  SPI_DEVICE = 1, the example works, but ONLY after I have run /usr/bin/fbi once to display an image. It appears that fbi does something that this script does not. No errors, just a blank screen

**Comment by ladyada** [comment]
hiya this is a bitbang version of the script - which isn't really supported - i think you want
https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install-2
:)

**Comment by svenyonson** [comment]
Yes, I am using SPI because I want the display to show a splash image on power up. fbi isn't available until later. I did run the script and set it as a raw framebuffer device. Everything works except that fbi needs to be run once before the bitbang works. Should be a simple call to make that I am missing.

**Comment by ladyada** [comment]
oh oof, hmm... i dont know :( maybe reset pin needs to be toggled? this code is very old and will be deprecated soon ...

**Comment by svenyonson** [comment]
Ok, I'll need to find a different solution. Surely there is a way to display an image on the TFT (ASAP) after the Pi powers up? Surely this is a common requirement for IoT type configurations?

**Comment by ladyada** [comment]
i dunno :( i think retropie has a splashscreen? but you have to boot linux before anythng shows up

**Comment by svenyonson** [comment]
This actually works fine, I had forgotten to enable the service. The screen shows up white for a second, but that's OK. Splash shows soon after.

[Unit]
Description=Splash screen
DefaultDependencies=no
After=local-fs.target

[Service]
ExecStart=/usr/bin/fbi -T 2 -d /dev/fb1 -noverbose -a /etc/micronets/splash.png
StandardInput=tty
StandardOutput=tty

[Install]
WantedBy=sysinit.target
