### ISSUE TITLE
ILI9340 port

### ISSUE THREAD

**Issue by Ivoah** [adafruit/Adafruit_Python_ILI9341#3]
I have ported this library to work with the ILI9340, what would be the best way to merge the two?

**Comment by makermelissa** [comment]
Hi, this library is being deprecated. We're now using https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display. You can find more info in our learn guide: 
https://learn.adafruit.com/adafruit-2-dot-8-color-tft-touchscreen-breakout-v2/python-wiring-and-setup
