### ISSUE TITLE
Memory leak in disp.clear()

### ISSUE THREAD

**Issue by Cellgalvano** [adafruit/Adafruit_Python_ILI9341#8]
I'm using the Library with a Raspberry Pi 2 and a cheap 2.4" display and I am getting an increase in memory everytime I call clear(). 

As a workaround i currently use the following change:

def clear(self, color=(0,0,0)):
        """Clear the image buffer to the specified RGB color (default black)."""
        width, height = self.buffer.size
        #self.buffer.putdata([color]_(width_height))
        draw = ImageDraw.Draw(self.buffer)
        draw.rectangle([(0,0),(width,height)], fill=color)
        del draw

As a side effect I'm getting higher framerates in my particular usecase.

**Comment by adtsys-suporte** [comment]
+1

**Comment by rojcosta** [comment]
I'm facing the same issue, but unfortunately @cellgalvano's workaround didn't work for me.

+1

**Comment by kfeger** [comment]
@Cellgalvano's fix worked for me like a charme!
Pi-Zero W, 2.8" China-TFT, python 2, Jessie
Thanks!!

**Comment by csiwek** [comment]
Indeed, there is a memory leak. It eats 0.2% of Bealglebone Black memory every time the clear() is called. 
After a while OOM killer kills the running process. You should open a PR with that (despite of seeing those are being ignored)

**Comment by svititom** [comment]
@rojcosta After updating the file, you have to run python setup install again

**Comment by makermelissa** [comment]
Hi, this library is being deprecated. We're now using https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display. You can find more info in our learn guide: 
https://learn.adafruit.com/adafruit-2-dot-8-color-tft-touchscreen-breakout-v2/python-wiring-and-setup
